### ISSUE TITLE
sandbox option

### ISSUE THREAD

**Issue by doctolivier** [daltonmenezes/interprocess#15]
Hey there! What an awesome project here, thank you for the great work.
I have just one question about the sandbox option. You use contextBridge and all setup required to make sandbox enabled but your documentation say that it need to be false. 
There is no way to use Interprocess with sandbox enabled? I need to keep my app securised with sandbox, but it really hard to have typescript definitions for ipc events.
Thank you!

**Comment by daltonmenezes** [comment]
Hi @doctolivier you can see my answer about that in the following discussion: #5
