### ISSUE TITLE
Unable to declare multiple parameters

### ISSUE THREAD

**Issue by seahindeniz** [daltonmenezes/interprocess#16]
Hi, according to type definitions, we can't use multiple parameters on main handlers however, multiple parameters are getting passed at runtime.

Here's an example
```ts
export const {
  ipcMain,
  ipcRenderer,
  exposeApiToGlobalWindow
} = createInterprocess({
  main: {
    async test(_, param1: string, param2: string) {
      return param1 + param2;
    }
  },

  renderer: {},
});
```
and the error
![image](https://github.com/daltonmenezes/interprocess/assets/5789670/1fb521e6-2eda-4ac8-8eec-1357ed007c77)

The only workaround is expecting an object with parameters/props. I'm not fan of using object for some curtain cases and it'd be best to have this DX improvement.

**Comment by daltonmenezes** [comment]
@seahindeniz the big problem is getting the types working correctly with an undefined number of parameters. Therefore, it is preferable to standardize and receive multiple data in one object.
