### ISSUE TITLE
Unsubscribe from handle

### ISSUE THREAD

**Issue by seahindeniz** [daltonmenezes/interprocess#17]
Hi, is there a way to unsubscribe from an event?
Let's say, I have the following methods
```ts
// ipcs.ts

export const {
  ipcMain,
  ipcRenderer,
  exposeApiToGlobalWindow
} = createInterprocess({
  main: {
    async doSomething() {
      console.log('some logic here and call window');

      const mainWindow = BrowserWindow.getAllWindows().find(
        window => window.title === '[main]'
      );

      if (mainWindow) {
        ipcMain.invoke.sendToWindow(mainWindow, `here's the data`);
      }
    }
  },

  renderer: {
    async sendToWindow(_, data: string) {
      console.log('incoming data', data);
    }
  },
});
```

```ts
// renderer.ts

window.api.handle.sendToWindow(async () => {
  console.log('this is second handler');
  window.api.remove.sendToWindow();
})
window.api.invoke.doSomething();
setTimeout(() => {
  window.api.invoke.doSomething();
}, 5000)
```

When it runs, the first callback suppose to remove `sendToWindow` and then after 5 seconds, it should pop an error says, there's no handler available but it doesn't. Because the latest event handler `window.api.handle.sendToWindow(async () => { });` has been registered in memory.
I believe this can also cause memory leak issue. 

Can a handle call `window.api.handle.sendToWindow(async () => {});` return a function to unsubscribe itself later on?

**Comment by daltonmenezes** [comment]
@seahindeniz I think I get it! If I remove the handler from the main process and try to invoke it from the renderer, I get the expected throw behavior, but if I remove the handler from the renderer process and try to invoke it from the main, it doesn't throw as expected! I'll investigate!

**Comment by daltonmenezes** [comment]
@seahindeniz done, please update to [v0.2.6](https://github.com/daltonmenezes/interprocess/releases/tag/v0.2.6)

**Comment by BaptisteBrument** [comment]
I think there is still an issue with this or I might be using the librairy wrong. I use v0.2.6
In my app.tsx I have the following : 
```ts
useEffect(() => {
		remove.action();
		handle.action(async () => {
			console.log("registered");
			return [state];
		});
		
	}, [state]);
```
But when I finally invoke it from my main process it still calls it multiple times.
