### ISSUE TITLE
Top-level imports are causing problems in renderer

### ISSUE THREAD

**Issue by seahindeniz** [daltonmenezes/interprocess#18]
Hello, 
I'm not sure if interprocess supports any other way to set handlers but following the suggested usage in https://github.com/daltonmenezes/interprocess#-usage section, and importing a dependency to use it in a handler that depends on `fsevents.node` creates a problem.
![image](https://github.com/daltonmenezes/interprocess/assets/5789670/fc65b74e-9590-4e83-8945-5c5ee046e61e)

Is there a way to separate the shared ipcs file into each scope so that imported modules won't get interfere with renderer/main scopes?

**Comment by daltonmenezes** [comment]
Hi @seahindeniz , you can try declaring dependencies like that as external, for example, in [electron-vite you can do this](https://electron-vite.org/guide/build.html#externals)!

Also, you can handle the handler as callback on main process, so you avoid imports that can't be joined on both process:
```ts
ipcMain.handle.getPing(async (_, { getPing, data }) => {
  // call the registered handler if needed
  const response = await getPing(_, data)

  await ipcMain.invoke.getPong(mainWindow, 'pong')

  ipcMain.remove.getPing()

  return 'The getPong ipc was removed'
})
```

**Comment by seahindeniz** [comment]
I'll try your suggestion. If it doesn't work out, I'll try to create a repro case

**Comment by daltonmenezes** [comment]
@seahindeniz any news?
