### ISSUE TITLE
error when `main` or `renderer` option is `undefined`

### ISSUE THREAD

**Issue by lamualfa** [daltonmenezes/interprocess#19]
# description

`main` and `renderer` options will make an error if one of them is empty. but the type says that both are optional.

<img width="587" alt="image" src="https://github.com/daltonmenezes/interprocess/assets/39755201/fed282af-f256-4eca-9a26-f9355c4184bd">

# example

## invalid (will produce the error above)

```ts
const { ipcMain, ipcRenderer, exposeApiToGlobalWindow } = createInterprocess({
  main: {},
})
```

## valid

```ts
const { ipcMain, ipcRenderer, exposeApiToGlobalWindow } = createInterprocess({
  main: {},
  renderer: {},
})
```

**Comment by lamualfa** [comment]
@daltonmenezes also, it's a good idea to emphasize the use of `sandbox: false` in `BrowserWindow`. the note in the comment section is too vague.

```js
app.whenReady().then(() => {
  const mainWindow = new BrowserWindow({
    webPreferences: {
      preload: path.join(__dirname, '../preload/index.js'),
      sandbox: false, // sandbox must be false
    },
  })

  handle.getPing()

  mainWindow.webContents.on('dom-ready', () => {
    invoke.getPong(mainWindow, 'pong')
  })
})
```
use this instead:

```js
app.whenReady().then(() => {
  const mainWindow = new BrowserWindow({
    webPreferences: {
      preload: path.join(__dirname, '../preload/index.js'),
      sandbox: false, // sandbox must be false
    },
  })

  handle.getPing()

  mainWindow.webContents.on('dom-ready', () => {
    invoke.getPong(mainWindow, 'pong')
  })
})
```
> **Important!** Don't forget to add `sandbox: false` to the `BrowserWindow` because it's required to load the preload script.

**Comment by daltonmenezes** [comment]
@lamualfa done, please update to [v0.2.6](https://github.com/daltonmenezes/interprocess/releases/tag/v0.2.6)
