### ISSUE TITLE
Typescript bug around types/index.ts

### ISSUE THREAD

**Issue by theogravity** [daltonmenezes/interprocess#7]
This is with me copying the src files directly to my project to get around `sandbox: true`, and using typescript 4.9.

The `IPC` type doesn't do anything with the `infer` variables, so TS complains.

<img width="744" alt="image" src="https://user-images.githubusercontent.com/855434/218624165-a0abf2b1-67b7-4339-9562-dd04be3fd250.png">

**Comment by daltonmenezes** [comment]
Hi @theogravity , I don't get any errors around this as you can see:
![Captura de tela de 2023-02-14 21-01-34](https://user-images.githubusercontent.com/1149845/218891290-997e1d50-8a87-4a63-9205-5d427471f1f6.png)

The development and build stages are not affected by that `never read` message and it makes the trick for the type inference, in this case I don't know if it's worth making changes. 🤔

**Comment by theogravity** [comment]
I think I know what's going on. We have a monorepo, but the package.json at the root which we use for eslint uses an older version of typescript (4.5), so when the IDE performs linting, it's using that version instead of the electron typescript ver.

Thanks for looking into this!
